CREATE TABLE PUB_AJ_JB
(
    AJXH int PRIMARY KEY NOT NULL,
    AH varchar(40),
    AJMC varchar(250),
    AJXZ char(10),
    AJLY char(10),
    SPCX char(10),
    SPCXDZ char(10),
    SYCX char(10),
    SFYS char(1),
    SFZDAJ char(1),
    SFJBAJ char(1),
    SFFHCS char(1),
    SFWDYJ char(1),
    SX int,
    FJSX int,
    LYDQ varchar(80),
    BASPT char(10),
    JYAQ text,
    LARQ datetime NULL ,
    LAR char(50),
    BAFY char(50),
    GKSJG char(50),
    CBRYJ text,
    HYTYJ text,
    TZHYJ text,
    YZHYJ text,
    SWHYJ text,
    JARQ datetime NULL ,
    JAFS char(10),
    JAYY char(100),
    JAYYDM char(10),
    BZ char(200),
    SXRQ datetime NULL ,
    GDBZ char(10),
    AJZT char(10),
    BYCXDZ varchar(10),
    AJWSQK varchar(10),
    GDRQ datetime NULL ,
    GDXLH int,
    CBRBPRQ datetime NULL ,
    SPZSQRQ datetime NULL ,
    HYTHYRQ datetime NULL ,
    TZSQRQ datetime NULL ,
    YZSQRQ datetime NULL ,
    SWHJDRQ datetime NULL ,
    YZQFRQ datetime NULL,
    SLQK varchar(10),
    SSLX varchar(10),
    SFGS char(1),
    FHCSYY varchar(10),
    GPYY varchar(10),
    JJAR varchar(10),
    SFZSCQ varchar(1),
    SWLX varchar(10),
    MODFLAG varchar(1),
    TRANSFLAG varchar(1),
    SPTG int,
    PSYCY varchar(1),
    MSAJTJS varchar(1),
    MSAJTJSSS varchar(1),
    SHWDFXPG char(10),
    SFXESS char(1),
    SFFCXX char(1),
    FXHJCS varchar(100),
    PJSFFDJFNR varchar(10),
    SFDTPJ varchar(10),
    SFHJ varchar(10),
    SFKTSL varchar(10),
    SFTZ varchar(10),
    SFCQYSCS char(1),
    AJSFYS char(1),
    RMPSYXM varchar(50),
    RMPSYID varchar(50),
    RMPSYID2 varchar(50),
    SFXSSC char(1),
    LYBM varchar(80),
    WJAWSYY varchar(2),
    PJJG varchar(10),
    JATHYY varchar(200)
)
    CREATE TABLE PUB_SPRY
(
    AJXH VARCHAR(30) NOT NULL,
    SPRYBH VARCHAR(30) NOT NULL,
    FG VARCHAR(10),
    SFCBR VARCHAR(2),
    SFSPZ VARCHAR(10),
    SFDLSPY VARCHAR(2),
    SFRMPSY char(1),
    XM VARCHAR(30),
    GH VARCHAR(30),
    BGYY VARCHAR(30),
    BGSJ datetime NULL ,
    BGFS VARCHAR(30),
    CONSTRAINT PUB_SPRY_11486352351 PRIMARY KEY (AJXH, SPRYBH)
);
-- auto-generated definition
CREATE TABLE PUB_XTGL_YHB
(
    YHBH VARCHAR(30) PRIMARY KEY NOT NULL,
    YHDM VARCHAR(30),
    YHMC VARCHAR(30),
    YHKL VARCHAR(30),
    YHBM varchar(20),
    KLTS varchar(40),
    KLDA varchar(20),
    YHSF varchar(20),
    KLSZSJ datetime,
    QJKSSJ datetime,
    QJJSSJ datetime,
    QJYY varchar(200),
    GRNZB int,
    QTNZB int,
    GRBAJS int,
    PHONE varchar(20),
    XFQX varchar(100),
    SSFWZXQX varchar(100),
    DZQM_ VARCHAR(30),
    JBXXJ_CODE varchar(30),
    FAZT int,
    FASL int,
    FYBH int,
    YHZT int,
    DZQMSCSJ datetime,
    COCALL varchar(20)
)
create DATABASE sqltest;
